name: mcm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - notebook
  - pip
  - pip:
    - plotly
    - sqlalchemy
    - pymysql
    - psycopg2-binary
    - python-dotenv
    - statsmodels
    - tqdm
